name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'repowiki/**' # Trigger when changes are made to the repowiki folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use a stable Node.js version

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'repowiki' # Specify the directory to deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
